backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "journal"
    label: "Journal"
    label_singular: "Post"
    folder: "src/content/journal"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Post Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Short preview (1â€“2 sentences)", name: "summary", widget: "text" }
      - { label: "Post", name: "body", widget: "markdown" }
      - { label: "Hide this post (draft)", name: "draft", widget: "boolean", default: false, required: false }